#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O HDMI-0

bspc monitor HDMI-0 -d I II III IV V VI

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color \#469CC3
bspc config focus_follows_pointer true

bspc rule -a copyq state=floating sticky=on
bspc rule -a floating state=floating

feh --bg-scale $HOME/.config/bspwm/wallpaper/wallpaper.png &
picom -b --config $HOME/.config/picom/picom.conf &
dunst &
setxkbmap -option grp:switch,grp:alt_shift_toggle,grp_led:scroll us,es &
copyq &
